## masyvai ir matricos

In [174]:
import numpy as np

In [175]:
sarasas = [2, 7, 5, 6, 12, 14, 15, 22, 3]

In [176]:
masyvas = np.array(sarasas)
print(masyvas, type(masyvas))

[ 2  7  5  6 12 14 15 22  3] <class 'numpy.ndarray'>


In [177]:
sugrupuotas = [[2, 7, 5], [6, 212, 14], [15, 1, 22]]

In [178]:
matrica = np.array(sugrupuotas)
print(matrica)

[[  2   7   5]
 [  6 212  14]
 [ 15   1  22]]


In [179]:
imtis = np.arange(0, 30, 3)
print(imtis, type(imtis))

[ 0  3  6  9 12 15 18 21 24 27] <class 'numpy.ndarray'>


In [180]:
nuliai = np.zeros(10)
print(nuliai)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [181]:
nuliai_matrica = np.zeros((6, 6))
print(nuliai_matrica)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [182]:
akis = np.eye(6)
print(akis)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [183]:
akis[0]
# pirmas stulpelis

array([1., 0., 0., 0., 0., 0.])

In [184]:
akis[0][0]
# pirmas simbolis

1.0

In [185]:
akis [0][3] = 3
akis [2][1] = 2
akis

array([[1., 0., 0., 3., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 2., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [186]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [187]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

## random arrays

In [188]:
np.random.rand(10)

array([0.60265335, 0.98788883, 0.84295524, 0.82975434, 0.72773259,
       0.06031677, 0.04002053, 0.86899955, 0.21098224, 0.52306089])

In [189]:
np.random.rand(10, 10)

array([[0.43287666, 0.30690915, 0.49839629, 0.37137867, 0.86616308,
        0.82282597, 0.91261224, 0.51442312, 0.23904284, 0.95427294],
       [0.02339226, 0.26123494, 0.21732415, 0.60821339, 0.66672991,
        0.23980268, 0.97396584, 0.8231469 , 0.4084982 , 0.04682261],
       [0.91635401, 0.0078018 , 0.50562152, 0.75148954, 0.88329391,
        0.21208227, 0.78341177, 0.9897908 , 0.87606619, 0.66542887],
       [0.00514635, 0.78170379, 0.75944314, 0.04536993, 0.70403941,
        0.49530515, 0.90463645, 0.69667556, 0.98494415, 0.54773153],
       [0.44597174, 0.43664031, 0.63381609, 0.65245544, 0.10508807,
        0.94603333, 0.82575727, 0.10758876, 0.96326543, 0.27246801],
       [0.64656911, 0.18496516, 0.29019561, 0.7251377 , 0.66243291,
        0.23572615, 0.48247476, 0.00968152, 0.04601884, 0.57654541],
       [0.23405227, 0.41886443, 0.40352776, 0.67507905, 0.67157529,
        0.59309391, 0.01713539, 0.01780304, 0.04184299, 0.89593657],
       [0.02964405, 0.96886219, 0.7814843

In [190]:
np.random.randn(5, 5) * 10

array([[ -6.04734015,   0.26670017,  -4.82626629,   4.8937347 ,
         -1.32016537],
       [-13.4639701 ,  -3.27712445, -11.94760188,   3.15144804,
        -10.51547296],
       [  8.81933345,  -4.70000229,  -8.96667779,  -6.2299968 ,
         14.58061144],
       [ 11.91587215,  -1.20561896,   1.28144167,  -0.93525219,
         -5.254744  ],
       [ 13.5603944 ,   6.17939101,   6.09518287,   3.20067777,
         -8.19685227]])

In [191]:
np.random.randint(100, 200, 10)

array([139, 185, 114, 194, 172, 167, 123, 103, 129, 105])

## masyvu pertvarka

In [192]:
betko_64 = np.random.randint(100, 999, 64)
betko_64

array([595, 495, 448, 649, 799, 840, 723, 113, 274, 171, 138, 771, 424,
       972, 161, 386, 804, 691, 610, 259, 305, 361, 700, 815, 456, 831,
       323, 869, 629, 655, 467, 567, 966, 805, 317, 830, 133, 783, 662,
       197, 207, 731, 992, 415, 139, 548, 470, 258, 451, 639, 249, 711,
       100, 868, 586, 929, 924, 553, 398, 144, 278, 829, 929, 221])

In [193]:
betko_8x8 = betko_64.reshape(8, 8)
betko_8x8

array([[595, 495, 448, 649, 799, 840, 723, 113],
       [274, 171, 138, 771, 424, 972, 161, 386],
       [804, 691, 610, 259, 305, 361, 700, 815],
       [456, 831, 323, 869, 629, 655, 467, 567],
       [966, 805, 317, 830, 133, 783, 662, 197],
       [207, 731, 992, 415, 139, 548, 470, 258],
       [451, 639, 249, 711, 100, 868, 586, 929],
       [924, 553, 398, 144, 278, 829, 929, 221]])

In [194]:
betko_20 = np.random.randint(100, 999, 20)
betko_4x5 = betko_20.reshape(4, 5)
print(betko_4x5)

[[743 263 773 809 736]
 [483 670 356 644 663]
 [734 109 616 994 360]
 [585 181 197 222 855]]


## naudingi metodai

In [195]:
# min(betko_64) <- python
betko_64.min()

100

In [196]:
# max(betko_20) <- python
betko_20.max()

994

In [197]:
print(betko_20.argmin(), betko_20.min())
#              vieta   ir       reiksme

11 109


In [198]:
print(betko_20.argmax(), betko_20.max())

13 994


In [199]:
betko_8x8.shape # kintamojo forma

(8, 8)

In [200]:
betko_20.shape

(20,)

In [201]:
betko_20.dtype # tipas

dtype('int32')

## indeksacija ir reiksmiu traukimas

In [202]:
betko_20

array([743, 263, 773, 809, 736, 483, 670, 356, 644, 663, 734, 109, 616,
       994, 360, 585, 181, 197, 222, 855])

In [203]:
betko_20[2]

773

In [204]:
betko_20[2:5]

array([773, 809, 736])

In [205]:
betko_20[::2]

array([743, 773, 736, 670, 644, 734, 616, 360, 181, 222])

In [206]:
betko_20[-5] = 777
# pakeicia reiksme

In [207]:
betko_20

array([743, 263, 773, 809, 736, 483, 670, 356, 644, 663, 734, 109, 616,
       994, 360, 777, 181, 197, 222, 855])

In [208]:
betko_8x8

array([[595, 495, 448, 649, 799, 840, 723, 113],
       [274, 171, 138, 771, 424, 972, 161, 386],
       [804, 691, 610, 259, 305, 361, 700, 815],
       [456, 831, 323, 869, 629, 655, 467, 567],
       [966, 805, 317, 830, 133, 783, 662, 197],
       [207, 731, 992, 415, 139, 548, 470, 258],
       [451, 639, 249, 711, 100, 868, 586, 929],
       [924, 553, 398, 144, 278, 829, 929, 221]])

In [209]:
# y, x reiksmes
betko_8x8[2,2:5]

array([610, 259, 305])

In [210]:
betko_8x8[2:-2, 2:-2]
# vidurys 4x4

array([[610, 259, 305, 361],
       [323, 869, 629, 655],
       [317, 830, 133, 783],
       [992, 415, 139, 548]])

In [211]:
betko_8x8[-3:, -3:]
# paskutines trys eilutes ir stulpeliai 3x3

array([[548, 470, 258],
       [868, 586, 929],
       [829, 929, 221]])

## reiksmiu traukimas pagal salyga

In [212]:
#  tiesos matrica
tiesa_8x8 = betko_8x8 > 500
tiesa_8x8

array([[ True, False, False,  True,  True,  True,  True, False],
       [False, False, False,  True, False,  True, False, False],
       [ True,  True,  True, False, False, False,  True,  True],
       [False,  True, False,  True,  True,  True, False,  True],
       [ True,  True, False,  True, False,  True,  True, False],
       [False,  True,  True, False, False,  True, False, False],
       [False,  True, False,  True, False,  True,  True,  True],
       [ True,  True, False, False, False,  True,  True, False]])

In [213]:
betko_8x8[tiesa_8x8]

array([595, 649, 799, 840, 723, 771, 972, 804, 691, 610, 700, 815, 831,
       869, 629, 655, 567, 966, 805, 830, 783, 662, 731, 992, 548, 639,
       711, 868, 586, 929, 924, 553, 829, 929])

In [214]:
betko_8x8[betko_8x8 < 200]

array([113, 171, 138, 161, 133, 197, 139, 100, 144])

### elgsenos ypatumai

In [215]:
betko_20

array([743, 263, 773, 809, 736, 483, 670, 356, 644, 663, 734, 109, 616,
       994, 360, 777, 181, 197, 222, 855])

In [216]:
ispjova = betko_20[5:-5]
ispjova

array([483, 670, 356, 644, 663, 734, 109, 616, 994, 360])

In [217]:
ispjova[:] = 999

In [218]:
betko_20

array([743, 263, 773, 809, 736, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 777, 181, 197, 222, 855])

In [219]:
kopija = betko_20.copy()
kopija

array([743, 263, 773, 809, 736, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 777, 181, 197, 222, 855])

In [220]:
kopija == betko_20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [221]:
kopijos_ispjova = kopija[5:-5]
kopijos_ispjova

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [222]:
kopijos_ispjova[:] = np.random.randint(100, 999, 10)

In [223]:
kopija

array([743, 263, 773, 809, 736, 185, 936, 693, 553, 558, 607, 644, 103,
       169, 639, 777, 181, 197, 222, 855])

In [224]:
kopija == betko_20

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True])

## matematines operacijos ir funkcijos

In [231]:
pirmi_10 = np.random.randint(0, 99, 10)
antri_10 = np.random.randint(0, 99, 10)
print(pirmi_10, antri_10)

[22 77 49 59 78 16 60 85 74 33] [31 82 40 42 16 51 42 45 32 68]


In [232]:
pirmi_10 + antri_10

array([ 53, 159,  89, 101,  94,  67, 102, 130, 106, 101])

In [233]:
pirmi_10 * antri_10

array([ 682, 6314, 1960, 2478, 1248,  816, 2520, 3825, 2368, 2244])

In [234]:
pirmi_10 / antri_10

array([0.70967742, 0.93902439, 1.225     , 1.4047619 , 4.875     ,
       0.31372549, 1.42857143, 1.88888889, 2.3125    , 0.48529412])

In [235]:
pirmi_10 ** 3

array([ 10648, 456533, 117649, 205379, 474552,   4096, 216000, 614125,
       405224,  35937], dtype=int32)

In [237]:
antri_10 ** 10

array([-1796951359,  2108376064,  1073741824, -2051251200,           0,
         695354697, -2051251200,  -655691255,           0,  -636485632],
      dtype=int32)

In [238]:
np.sin(pirmi_10)

array([-0.00885131,  0.99952016, -0.95375265,  0.63673801,  0.51397846,
       -0.28790332, -0.30481062, -0.17607562, -0.98514626,  0.99991186])

In [239]:
np.log(pirmi_10)

array([3.09104245, 4.34380542, 3.8918203 , 4.07753744, 4.35670883,
       2.77258872, 4.09434456, 4.44265126, 4.30406509, 3.49650756])