In [2]:
import numpy as np

In [3]:
sarasas = np.arange(1, 10)
sarasas

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
nuliai = np.zeros(10)
nuliai

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
vienetai = np.ones(10)
vienetai

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
ketvertai = np.full(10, 4)
ketvertai

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [7]:
lyginiai = np.arange(0, 101, 2)
lyginiai

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [8]:
matrica = np.array(range(1, 26)).reshape(5, 5)
matrica

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
matrica[2, 1]

12

In [10]:
matrica[-1]

array([21, 22, 23, 24, 25])

In [11]:
matrica[0:3, 0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [12]:
matrica[1:-1, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [13]:
matrica[3:, :-2]

array([[16, 17, 18],
       [21, 22, 23]])

In [14]:
random_20 = np.random.rand(20)
random_20

array([0.04390475, 0.93462424, 0.4427374 , 0.16787071, 0.19269642,
       0.8755481 , 0.47601525, 0.25341141, 0.59566763, 0.28016325,
       0.3211309 , 0.98941264, 0.32558411, 0.13900256, 0.8770659 ,
       0.84260859, 0.86167299, 0.52699028, 0.92757754, 0.45429479])

In [15]:
print(random_20.max(), random_20.argmax())

0.9894126393643451 11


In [16]:
print(random_20.min(), random_20.argmin())

0.04390474775138331 0


In [17]:
random_20.dtype

dtype('float64')

In [18]:
iki_100 = np.arange(1, 101)
iki_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
nuo_90 = iki_100 > 90
iki_100[nuo_90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [20]:
kartotinis_7 = iki_100 % 7 == 0
iki_100[kartotinis_7]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [21]:
iki_1 = np.linspace(0.025, 1, 40).reshape(5, 8)
iki_1

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [22]:
iki_1000 = np.arange(2, 1001)
sveika_saknis = iki_1000 ** 0.5 % 1 == 0
iki_1000[sveika_saknis].reshape(6, 5)

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

### BONUS

In [23]:
bonus = np.arange(1, 101)
bonus

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [58]:
def pirminis(skaiciai):
  for skaicius in range(2, skaiciai):
    if skaiciai % skaicius == 0:
      return False
  return True

In [59]:
pirminiu_sarasas = np.vectorize(pirminis)

In [66]:
bonus[pirminiu_sarasas(bonus)]

array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])