In [1]:
import numpy as np

In [5]:
sarasas = np.arange(1, 10)
sarasas

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
nuliai = np.zeros(10)
nuliai

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
vienetai = np.ones(10)
vienetai

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
ketvertai = np.full(10, 4)
ketvertai

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [14]:
lyginiai = np.arange(0, 101, 2)
lyginiai

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [21]:
matrica = np.array(range(1, 26)).reshape(5, 5)
matrica

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
matrica[2, 1]

12

In [27]:
matrica[-1]

array([21, 22, 23, 24, 25])

In [28]:
matrica[0:3, 0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [34]:
matrica[1:-1, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [36]:
matrica[3:, :-2]

array([[16, 17, 18],
       [21, 22, 23]])

In [38]:
random_20 = np.random.rand(20)
random_20

array([0.85143503, 0.30747501, 0.32920621, 0.30246941, 0.13515926,
       0.22558548, 0.95525512, 0.51876907, 0.12166387, 0.91830152,
       0.44036014, 0.06928129, 0.09671096, 0.09598084, 0.49703623,
       0.51013279, 0.31527586, 0.45465263, 0.30907091, 0.86080192])

In [40]:
print(random_20.max(), random_20.argmax())

0.9552551201639748 6


In [41]:
print(random_20.min(), random_20.argmin())

0.06928128698055946 11


In [42]:
random_20.dtype

dtype('float64')

In [44]:
iki_100 = np.arange(1, 101)
iki_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [47]:
nuo_90 = iki_100 > 90
iki_100[nuo_90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [48]:
kartotinis_7 = iki_100 % 7 == 0
iki_100[kartotinis_7]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [68]:
iki_1 = np.linspace(0.025, 1, 40).reshape(5, 8)
iki_1

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [81]:
iki_1000 = np.arange(2, 1001)
sveika_saknis = iki_1000 ** 0.5 % 1 == 0
iki_1000[sveika_saknis].reshape(6, 5)

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

### BONUS

In [84]:
bonus = np.arange(1, 101)
bonus

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [85]:
def pirminis():
    pirminiu_sarasas = []
    for skaicius in bonus:
        if skaicius == 0 or skaicius == 1:
            break
        for i in range(skaicius -1, 1, -1):
            if skaicius % i == 0:
                break
        else:
            pirminiu_sarasas.append(skaicius)
    print(pirminiu_sarasas)